FROM ubuntu:focal

RUN apt-get update -y && apt-get -y install wget gnupg2 lsb-release
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
RUN sh -c 'echo "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/kitware.list'
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update -y && apt-get -y install git cmake debhelper \
    make build-essential postgresql-server-dev-all libpam-dev libzstd-dev zlib1g-dev
RUN cd /opt && git clone https://github.com/yandex/odyssey.git
WORKDIR /opt/odyssey
RUN make local_build && \
    rm odyssey.conf && \
    wget https://raw.githubusercontent.com/dimarudik/demo/minikube/k8s/odyssey-prepared/odyssey.conf
RUN dpkg-buildpackage -us -uc
WORKDIR /opt/odyssey

ENTRYPOINT ["./build/sources/odyssey","odyssey.conf"]

#docker build -t dimarudik/odyssey-package -f Dockerfile-odyssey .