apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  postgres_db                         : "postgres"
  postgres_host_auth_method           : "md5"
  pgbouncer_database                  : "*"
  pgbouncer_auth_user                 : "postgres"
  pgbouncer_port_t                    : "6432"
  pgbouncer_port_s                    : "7432"
  pgbouncer_pool_mode_s               : "session"
  pgbouncer_pool_mode_t               : "transaction"
  postgresql_host                     : "localhost"
  pgbouncer_auth_query                : "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
  pgbouncer_auth_type                 : "md5"
  pgbouncer_ignore_startup_parameters : "extra_float_digits"
  jar_args                            : "jdbc:postgresql://odyssey-transaction.default.svc.cluster.local:8432/postgres?user=test&password=test"
