apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db
spec:
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
# POSTGRESQL DB
        - name: app-db
          image: {{ .Values.container.image }}:{{ .Values.container.imageTag }}
          args: ["-c", "password_encryption=md5", "-c", "wal_level=logical", "-c", "log_min_duration_statement=10000", "-c", "log_statement=ddl", "-c", "log_directory=pg_log", "-c", "log_filename=%u_%a.log", "-c", "logging_collector=on", "-c", "wal_log_hints=on"]
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : postgres_db
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : postgres_host_auth_method
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name  : secret
                  key   : username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name  : secret
                  key   : password
###### POOLS
# pgbouncer transaction
        - name: pgbouncer-transaction
          image: bitnami/pgbouncer:latest
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 6432
          env:
            - name: PGBOUNCER_PORT
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_port_t
            - name: POSTGRESQL_HOST
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : postgresql_host
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name  : secret
                  key   : pgbusertran
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name  : secret
                  key   : pgbpswdtran
            - name: PGBOUNCER_POOL_MODE
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_pool_mode_t
            - name: PGBOUNCER_DATABASE
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_database
            - name: PGBOUNCER_AUTH_USER
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_auth_user
            - name: PGBOUNCER_AUTH_QUERY
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_auth_query
            - name: PGBOUNCER_AUTH_TYPE
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_auth_type
            - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_ignore_startup_parameters
# pgbouncer session
        - name: pgbouncer-session
          image: bitnami/pgbouncer:latest
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 7432
          env:
            - name: PGBOUNCER_PORT
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_port_s
            - name: POSTGRESQL_HOST
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : postgresql_host
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name  : secret
                  key   : username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name  : secret
                  key   : password
            - name: PGBOUNCER_POOL_MODE
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_pool_mode_s
            - name: PGBOUNCER_DATABASE
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_database
            - name: PGBOUNCER_AUTH_USER
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_auth_user
            - name: PGBOUNCER_AUTH_QUERY
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_auth_query
            - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
              valueFrom:
                configMapKeyRef:
                  name  : configmap
                  key   : pgbouncer_ignore_startup_parameters
# odyssey transaction
        - name: odyssey
          image: dimarudik/odyssey:latest
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 8432
# odyssey-noprepared transaction
        - name: odyssey-noprepared
          image: dimarudik/odyssey-noprepared:latest
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 9432
---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: app2odyssey
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: app2odyssey
#  template:
#    metadata:
#      labels:
#        app: app2odyssey
#    spec:
#      containers:
#        - name: app2odyssey
#          image: dimarudik/odyssey-prepared:latest
#          env:
#            - name: JAR_ARGS
#              valueFrom:
#                configMapKeyRef:
#                  name  : configmap
#                  key   : jar_args_odyssey
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: app2pgbouncer
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: app2pgbouncer
#  template:
#    metadata:
#      labels:
#        app: app2pgbouncer
#    spec:
#      containers:
#        - name: app2pgbouncer
#          image: dimarudik/odyssey-prepared:latest
#          env:
#            - name: JAR_ARGS
#              valueFrom:
#                configMapKeyRef:
#                  name  : configmap
#                  key   : jar_args_pgbouncer
#---
