apiVersion: v1
kind: Service
metadata:
  name: postgresql-db
spec:
  selector:
    app: app-db
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-transaction
spec:
  selector:
    app: app-db
  ports:
    - name: tcp
      protocol: TCP
      port: 6432
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-session
spec:
  selector:
    app: app-db
  ports:
    - name: tcp
      protocol: TCP
      port: 7432
---
apiVersion: v1
kind: Service
metadata:
  name: odyssey-transaction
spec:
  selector:
    app: app-db
  ports:
    - name: tcp
      protocol: TCP
      port: 8432
